[package]
name = "roc-fuzz"
version = "0.1.0"
authors = ["Brendan Hansknecht"]
description = "Native cargo-fuzz host ABI for the Roc fuzzing platform"
license = "MIT"
edition = "2021"
links = "roc-fuzz"
repository = "https://github.com/lukewilliamboswell/roc-fuzz"
readme = "README.md"
keywords = ["roc", "fuzzing", "testing"]
categories = ["development-tools::testing"]

[workspace]
