app [target] { fuzz: platform "https://github.com/lukewilliamboswell/roc-fuzz/releases/download/0.4.0-rc1/9k2cfuAWoBfcRBRiVbriXFf1dHktoRBbieifYN7NmTHc.tar.zst", roc: "nightly-2026-09-07-14d9829" }

import fuzz.Fuzz

Input : { bytes : List(U8), radix : U8 }

generator : Fuzz.Generator(Input)
generator = {
	bytes: Fuzz.bytes,
	radix: Fuzz.u8_in(2, 36),
}.Fuzz

test : Input -> Fuzz.Outcome
test = |input| {
	if List.len(input.bytes) >= 4 {
		crash "four generated bytes reproduce the failure artifact test"
	} else {
		Fuzz.keep
	}
}

target = Fuzz.target_with({
	name: "crashing-target",
	generator,
	test,
	show: |input| Str.inspect(input),
})
