name: Nightly configuration
on:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  configuration:
    uses: lukewilliamboswell/roc-automation/.github/workflows/check-config.yml@5af80ef9d9cf93f4000633adf4e33828d0ee88c8 # compiler-manifest
