name: Update Roc nightly
on:
  schedule:
    - cron: "28 13 * * *"
  workflow_dispatch:
permissions: {}
concurrency:
  group: roc-nightly-update
  cancel-in-progress: false
jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
      actions: write
      statuses: write
    uses: lukewilliamboswell/roc-automation/.github/workflows/update-roc-nightly.yml@da36cb354ccf501fc5fb140659a9f45f5445afa4 # compiler-manifest
