name: Update Roc nightly
on:
  schedule:
    - cron: "28 13 * * *"
  workflow_dispatch:
permissions: {}
concurrency:
  group: roc-nightly-update
  cancel-in-progress: false
jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
      actions: write
      statuses: write
    uses: lukewilliamboswell/roc-automation/.github/workflows/update-roc-nightly.yml@31f05e90fddeda335e7d9c9c0a34a8830c9d7170 # 31f05e9
