name: Update Roc nightly
on:
  schedule:
    - cron: "28 13 * * *"
  workflow_dispatch:
permissions: {}
concurrency:
  group: roc-nightly-update
  cancel-in-progress: false
jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
      actions: write
      statuses: write
    uses: lukewilliamboswell/roc-automation/.github/workflows/update-roc-nightly.yml@5af80ef9d9cf93f4000633adf4e33828d0ee88c8 # compiler-manifest
